<a href="https://colab.research.google.com/github/Hemanth160425/nlpbasics/blob/main/nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# punkt is a tokenizer for many languages .

In [ ]:
corpus = """ hello welcome to google colab . today our topic is about tokenization . this cover most of the topics"""

In [ ]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize

In [ ]:
doc=sent_tokenize(corpus)

In [ ]:
for s in doc:
  print(word_tokenize(s))

['hello', 'welcome', 'to', 'google', 'colab', '.']
['today', 'our', 'topic', 'is', 'about', 'tokenization', '.']
['this', 'cover', 'most', 'of', 'the', 'topics']


In [ ]:
word_tokenize(corpus)

['hello',
 'welcome',
 'to',
 'google',
 'colab',
 '.',
 'today',
 'our',
 'topic',
 'is',
 'about',
 'tokenization',
 '.',
 'this',
 'cover',
 'most',
 'of',
 'the',
 'topics']

In [ ]:
from nltk.tokenize import TreebankWordTokenizer
t=TreebankWordTokenizer()

In [ ]:
t.tokenize(corpus)

['hello',
 'welcome',
 'to',
 'google',
 'colab',
 '.',
 'today',
 'our',
 'topic',
 'is',
 'about',
 'tokenization',
 '.',
 'this',
 'cover',
 'most',
 'of',
 'the',
 'topics']

In [ ]:
# @title Stemming

# Definition: Stemming is the process of reducing a word to its base or root form by removing suffixes or prefixes.

# Purpose: It helps in reducing different forms of a word to a common base, improving the performance of text analysis tasks like search, classification, and clustering.

# Applications: Commonly used in Natural Language Processing (NLP), information retrieval, and search engines to match words with the same root despite having different suffixes (e.g., "running" becomes "run").

# Algorithm Types: Popular stemming algorithms include the Porter Stemmer, Snowball Stemmer, and Lancaster Stemmer.

# Porter Stemmer: A widely used and influential algorithm that removes common suffixes using a series of rules, but it can be somewhat conservative.

# Lancaster Stemmer: An aggressive stemmer that may over-stem words, making them too general (e.g., "maximum" becomes "max").

# Efficiency: Stemming reduces the number of unique terms in a text corpus, thus saving storage space and computational resources.

# Overstemming and Understemming: Overstemming leads to too many words being reduced to the same root, while understemming leaves too many variations of the same word.

# Difference from Lemmatization: Unlike stemming, lemmatization uses vocabulary and morphological analysis of words to return the dictionary form (lemma) rather than just removing prefixes or suffixes.

# Limitations: Stemming may not always produce real words (e.g., "fishing" becomes "fish," but "happiness" may become "happi"), which can lead to confusion in some applications.

In [ ]:
from nltk.stem import PorterStemmer
t=['eat','eats','eating']
for k in t:
  print(PorterStemmer().stem(k))

eat
eat
eat


In [ ]:
# diffretn types of stem are porter , snowball , lancaster , etc

In [ ]:
# @title Stemming

# Definition: Lemmatization is the process of reducing a word to its base or dictionary form, known as the "lemma," based on its meaning and context.

# Purpose: It helps in normalizing words by mapping inflected forms to a common base form, improving the accuracy of text analysis tasks like search, sentiment analysis, and language translation.

# Applications: Used in Natural Language Processing (NLP) tasks such as tokenization, text classification, information retrieval, and search engines to process and analyze textual data.

# Context-Aware: Unlike stemming, lemmatization considers the part of speech (POS) and context to determine the correct base form (e.g., "better" is lemmatized to "good" if used as an adjective).

# Uses a Dictionary: Lemmatization relies on a morphological dictionary or vocabulary to identify the correct lemma of a word (e.g., "better" is linked to "good").

# POS Tagging: To lemmatize correctly, words need to be tagged with their part of speech, as this influences the base form (e.g., "running" as a verb is reduced to "run," but as a noun remains "running").

# More Accurate than Stemming: Lemmatization is more precise because it returns actual words in their base form, whereas stemming may result in incorrect or incomplete words.

# Slower than Stemming: Due to its complexity and the need for POS tagging and dictionary lookup, lemmatization is typically slower and more resource-intensive than stemming.

# Difference from Stemming: Stemming only removes suffixes and prefixes without considering context, while lemmatization involves deeper linguistic analysis to ensure the base word is meaningful.

# Popular Libraries: Lemmatization tools are available in libraries like NLTK (Natural Language Toolkit) and spaCy, commonly used for NLP tasks in Python.

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
WordNetLemmatizer().lemmatize('going')

[nltk_data] Downloading package wordnet to /root/nltk_data...


'going'

In [ ]:
WordNetLemmatizer().lemmatize('going',pos='v')

'go'

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
para='''Natural language processing (NLP) is a branch of artif
icial intelligence that focuses on the interaction between computers a
nd humans through language. It involves enabling machines to understand, interpret,
 and generate human language in a way that is both meaningful and useful. Applications
 of NLP include language translation, sentiment analysis, and chatbot development, among
 others. With advancements in deep learning and machine learning algorithms, NLP has seen
 tremendous growth in recent years, enabling more sophisticat
ed models that can perform tasks such as text classification, named entity recognition, and question-answering with high accuracy.'''

In [ ]:
sentences=nltk.sent_tokenize(para)

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

# Example sentences
sentences = ["Natural language processing is fascinating.", "It involves both linguistics and computer science."]

# Ensure stopwords are downloaded
nltk.download('stopwords')
nltk.download('punkt')

# Initialize the PorterStemmer
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))
# Loop through each sentence
for i in range(len(sentences)):
    # Tokenize the sentence
    words = word_tokenize(sentences[i])

    # Apply stemming and remove stopwords
    words = [ps.stem(word) for word in words if word.lower() not in stop_words]

    # Join the words back into a sentence
    sentences[i] = ' '.join(words)

# Output the processed sentences
print(sentences)


['natur languag process fascin .', 'involv linguist comput scienc .']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
sentences[0]

'natur languag process fascin .'

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Example sentences
sentences = ["Natural language processing is fascinating.", "It involves both linguistics and computer science."]

# Ensure necessary NLTK data is downloaded
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Initialize the WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# Loop through each sentence
for i in range(len(sentences)):
    # Tokenize the sentence
    words = word_tokenize(sentences[i])

    # Set of stopwords
    stop_words = set(stopwords.words('english'))

    # Apply lemmatization and remove stopwords
    words = [lemmatizer.lemmatize(word.lower()) for word in words if word.lower() not in stop_words]

    # Join the words back into a sentence
    sentences[i] = ' '.join(words)

# Output the processed sentences
print(sentences)


['natural language processing fascinating .', 'involves linguistics computer science .']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [ ]:
sentences[0]

'natural language processing fascinating .'

In [ ]:

import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
import nltk
from nltk.corpus import stopwords

sentences = ["Natural language processing is fascinating.", "It involves both linguistics and computer science."]

lemmatizer = WordNetLemmatizer()

for i in range(len(sentences)):
    # Tokenize the sentence
    words = word_tokenize(sentences[i])

    # Set of stopwords
    stop_words = set(stopwords.words('english'))


    words = [word for word in words if word.lower() not in stop_words]

    poss_tag=nltk.pos_tag(words)
    print(poss_tag)


[('Natural', 'JJ'), ('language', 'NN'), ('processing', 'NN'), ('fascinating', 'NN'), ('.', '.')]
[('involves', 'NNS'), ('linguistics', 'NNS'), ('computer', 'NN'), ('science', 'NN'), ('.', '.')]


In [ ]:
import nltk
nltk.download('words')

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

In [ ]:
# name entity recogniton
import nltk
nltk.download('maxent_ne_chunker')
s = "Natural language processing is fascinating. It involves both linguistics and computer science."

t=nltk.word_tokenize(s)

poss_tag=nltk.pos_tag(t)
nltk.ne_chunk(poss_tag).draw


[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!


<bound method Tree.draw of Tree('S', [('Natural', 'JJ'), ('language', 'NN'), ('processing', 'NN'), ('is', 'VBZ'), ('fascinating', 'VBG'), ('.', '.'), ('It', 'PRP'), ('involves', 'VBZ'), ('both', 'DT'), ('linguistics', 'NNS'), ('and', 'CC'), ('computer', 'NN'), ('science', 'NN'), ('.', '.')])>

In [ ]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
voc_size=500
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[241, 382, 176, 80], [241, 382, 176, 294], [241, 153, 176, 305], [499, 152, 41, 117, 280], [499, 152, 41, 117, 437], [483, 241, 389, 176, 80], [166, 212, 109, 117]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 241 382 176  80]
 [  0   0   0   0 241 382 176 294]
 [  0   0   0   0 241 153 176 305]
 [  0   0   0 499 152  41 117 280]
 [  0   0   0 499 152  41 117 437]
 [  0   0   0 483 241 389 176  80]
 [  0   0   0   0 166 212 109 117]]


In [ ]:
## 10 feature dimesnions
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 241, 382, 176,  80], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step


array([[ 0.048448  ,  0.00498738,  0.00416286,  0.03011911,  0.03405705,
         0.00312258,  0.01926457, -0.00547083, -0.01265547,  0.00722307],
       [ 0.048448  ,  0.00498738,  0.00416286,  0.03011911,  0.03405705,
         0.00312258,  0.01926457, -0.00547083, -0.01265547,  0.00722307],
       [ 0.048448  ,  0.00498738,  0.00416286,  0.03011911,  0.03405705,
         0.00312258,  0.01926457, -0.00547083, -0.01265547,  0.00722307],
       [ 0.048448  ,  0.00498738,  0.00416286,  0.03011911,  0.03405705,
         0.00312258,  0.01926457, -0.00547083, -0.01265547,  0.00722307],
       [-0.01878327,  0.00802612, -0.01391339, -0.00739123,  0.02204578,
         0.04552731,  0.01223477, -0.0288033 , -0.01654165, -0.01644988],
       [-0.0236474 ,  0.02278558, -0.0269809 ,  0.0411031 ,  0.03689874,
        -0.03080672, -0.03566187,  0.02934027, -0.00027283,  0.00322007],
       [-0.02831816, -0.03966511,  0.03793517,  0.02296552,  0.02983199,
         0.01588723,  0.02574766,  0.02331244

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0, 241, 382, 176,  80], dtype=int32)